### Get all

GET http://localhost:3001/api/getall

### Add new item

POST http://localhost:3001/api/add
Content-Type: application/json

{
    "name": "Oivariini 500g",
    "price": 3
}


### Get item using id
GET http://localhost:3001/api/6274ffb8cddc3cff64b0dab6

### Delete item using id

DELETE http://localhost:3001/api/delete/627529afdf8f3317fe5b1bfe

### Update one or many fields of an item using id (PATCH)

PATCH http://localhost:3001/api/update/6274fd84065f0e2e66e55af0
Content-Type: application/json

{
    "name": "Rae juusto Valio 120g",
    "price": 1.90
}